package io.github.tamawish.rwr.reset;

public enum ResetFailureType {
    UNKNOWN_WORLD_ID,
    WORLD_NOT_MANAGED,
    WORLD_BUSY,
    GLOBAL_RESET_BUSY,
    EVENT_CANCELLED,
    WORLD_NOT_REGISTERED,
    WORLD_NOT_LOADED,
    WORLD_IDENTITY_CHANGED,
    EVACUATION_DISABLED,
    EVACUATION_DESTINATION_UNAVAILABLE,
    EVACUATION_FAILED,
    PLAYERS_REMAINING,
    MULTIVERSE_REJECTED,
    MULTIVERSE_DELETE_FAILED,
    MULTIVERSE_CREATE_FAILED,
    MULTIVERSE_API_EXCEPTION,
    VERIFICATION_FAILED,
    JOURNAL_UNAVAILABLE,
    INTERRUPTED_OPERATION
}
