package io.github.tamawish.rwr.reset;

import com.google.gson.annotations.SerializedName;

/** Normalized failure categories produced by the reset workflow. */
public enum ResetFailureType {
  UNKNOWN_WORLD_ID,
  WORLD_NOT_MANAGED,
  WORLD_BUSY,
  GLOBAL_RESET_BUSY,
  EVENT_CANCELLED,
  WORLD_NOT_REGISTERED,
  WORLD_NOT_LOADED,
  WORLD_IDENTITY_CHANGED,
  EVACUATION_DISABLED,
  EVACUATION_DESTINATION_UNAVAILABLE,
  EVACUATION_FAILED,
  PLAYERS_REMAINING,
  @SerializedName(value = "PROVIDER_REJECTED", alternate = "MULTIVERSE_REJECTED")
  PROVIDER_REJECTED,
  @SerializedName(value = "PROVIDER_DELETE_FAILED", alternate = "MULTIVERSE_DELETE_FAILED")
  PROVIDER_DELETE_FAILED,
  @SerializedName(value = "PROVIDER_CREATE_FAILED", alternate = "MULTIVERSE_CREATE_FAILED")
  PROVIDER_CREATE_FAILED,
  @SerializedName(value = "PROVIDER_API_EXCEPTION", alternate = "MULTIVERSE_API_EXCEPTION")
  PROVIDER_API_EXCEPTION,
  VERIFICATION_FAILED,
  JOURNAL_UNAVAILABLE,
  INTERRUPTED_OPERATION
}
